// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAesELlvI7mg31EE_IkxCp9RPLJ11rz2Zs',
    appId: '1:646025945964:web:27177d9dac92c22d070949',
    messagingSenderId: '646025945964',
    projectId: 'sbi-auth-cb8bf',
    authDomain: 'sbi-auth-cb8bf.firebaseapp.com',
    storageBucket: 'sbi-auth-cb8bf.appspot.com',
    measurementId: 'G-XF6P3JZXM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDlaCXhGUZ-BuYC9Ljvco2r1V6hNH9BKg',
    appId: '1:646025945964:android:7be9f2bb4caa7b3f070949',
    messagingSenderId: '646025945964',
    projectId: 'sbi-auth-cb8bf',
    storageBucket: 'sbi-auth-cb8bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUX13A73gBgNi_fwMRdFzqCMdrxzekI4',
    appId: '1:646025945964:ios:9c049431c80ab9ec070949',
    messagingSenderId: '646025945964',
    projectId: 'sbi-auth-cb8bf',
    storageBucket: 'sbi-auth-cb8bf.appspot.com',
    iosBundleId: 'com.example.sbi',
  );
}
